### PR TITLE
Update url shcema

### PR DESCRIPTION
**Pull request by marcusmolchany**
cleaned up git history of https://github.com/Fullscreen/filterjitsu/pull/26

### CODE REVIEW

**Comment by marcusmolchany** [comment]
closes https://github.com/Fullscreen/filterjitsu/issues/9

**Comment by philipqnguyen** [comment]
Just one thing, in index.html, clear "Clear search query params" doesn't actually work...

**Comment by marcusmolchany** [comment]
hm really? its working for me

**Comment by philipqnguyen** [comment]
Scratch that, it works =D

**Comment by marcusmolchany** [comment]
👌

**Pull request merged**
